# Generated by Django 3.1.6 on 2021-02-06 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=250, null=True, verbose_name='Imię')),
                ('lastname', models.CharField(max_length=250, null=True, verbose_name='Nazwisko')),
                ('nickname', models.CharField(max_length=250, null=True, verbose_name='Pseudonim')),
                ('birthdate', models.DateTimeField(null=True, verbose_name='Data urodzenia')),
            ],
            options={
                'verbose_name': 'Pisarz',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, null=True, verbose_name='Tytuł')),
                ('pages_num', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Liczba stron')),
                ('cover_image', models.ImageField(default='imgs/none.jpg', upload_to='imgs/', verbose_name='Okładka')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Data modyfikacji')),
            ],
            options={
                'verbose_name': 'Książka',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True, verbose_name='Nazwa')),
            ],
            options={
                'verbose_name': 'Wydawca',
            },
        ),
        migrations.CreateModel(
            name='BookAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookstore.author', verbose_name='Autorzy')),
                ('book_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookstore.book', verbose_name='Ksiązki')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autorzy',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='publisher_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookstore.publisher', verbose_name='Wydawca'),
        ),
    ]
