# Generated by Django 3.1.6 on 2021-02-06 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Pisarz', 'verbose_name_plural': 'Pisarze'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Książka', 'verbose_name_plural': 'Książki'},
        ),
        migrations.AlterModelOptions(
            name='publisher',
            options={'verbose_name': 'Wydawca', 'verbose_name_plural': 'Wydawcy'},
        ),
        migrations.RenameField(
            model_name='book',
            old_name='publisher_id',
            new_name='publisher',
        ),
        migrations.RemoveField(
            model_name='bookauthor',
            name='author_id',
        ),
        migrations.RemoveField(
            model_name='bookauthor',
            name='book_id',
        ),
        migrations.AddField(
            model_name='bookauthor',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='bookstore.author', verbose_name='Autorzy'),
        ),
        migrations.AddField(
            model_name='bookauthor',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authors', to='bookstore.book', verbose_name='Ksiązki'),
        ),
        migrations.AlterField(
            model_name='author',
            name='birthdate',
            field=models.DateField(null=True, verbose_name='Data urodzenia'),
        ),
    ]
